name: Dependency Updates

on:
  schedule:
    # Run weekly on Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    
    - name: Update project dependencies
      working-directory: aihero/project
      run: |
        uv lock --upgrade
    
    - name: Update course dependencies
      working-directory: aihero/course
      run: |
        uv lock --upgrade
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "chore: update dependencies"
        title: "chore: automated dependency updates"
        body: |
          Automated dependency updates by GitHub Actions.
          
          This PR updates the following:
          - Python package dependencies in both aihero/project and aihero/course
          - uv.lock files with latest compatible versions
          
          Please review the changes and ensure all tests pass before merging.
        branch: dependency-updates
        delete-branch: true